name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Nécessaire pour pousser sur gh-pages
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilise le token automatique
          fetch-depth: 0  # Important pour gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # Plus fiable que npm install

      - name: Build and Deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Passe le token à gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm run build
          npm run deploy